remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: spicydata.io
description: spicy data for the masses
show_downloads: false
google_analytics:
